modLoader="javafml" #mandatory
loaderVersion="[26,)" #mandatory (26 is current forge version)
issueTrackerURL="https://github.com/CJ-MC-Mods/Overloaded/issues"

[[mods]]
    modId="overloaded"
    namespace="overloaded"
    version="${version}"
    displayName="Overloaded"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/overloaded"
    logoFile="logo.png"
    credits="Assets: Mega___Byte | Documentation / Thinkers: Sironin, Braingkk"
    authors="CJ Miller (cjm721)"
    description='''
    Adds various complicated and tedious things that will minimize your need to destroy your server with your chunk sized arrays of machines.

    Almost all balance values can be configured.
    '''
    [[dependencies.overloaded]] #optional
        modId="forge" #mandatory
        mandatory=true #mandatory
        versionRange="[26,)" #mandatory
        ordering="NONE"
        side="BOTH"